version: '2.4'

services:
  student-api-base:
    image: student-api-base-image
    build:
      context: .
    container_name: student-api-base
    volumes:
      - .:/app
    environment:
      - VIRTUAL_HOST=student-api.docker # Postgres connectivity
      - PGHOST=students-postgres
      - PGPORT=5432
      - PGDATABASE=students
      - PGUSER=students
      - PGPASSWORD=password

    command: [ "echo", "base build done" ]

  student-api:
    extends: student-api-base
    container_name: student-api
    depends_on:
      - students-postgres
    command:
      [
        "uvicorn",
        "--reload",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "student-api.main:app"
      ]
  students-postgres:
    container_name: students-postgres
    image: postgres:12.5
    environment:
      VIRTUAL_HOST: students-postgres.docker
      POSTGRES_DB: students
      POSTGRES_USER: students
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
