"""add addresses table

Revision ID: 0c46710fd6db
Revises: 07b2088a3a72
Create Date: 2022-01-09 15:13:53.642546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c46710fd6db'
down_revision = '07b2088a3a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
                    sa.Column('email_id', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('user_id', postgresql.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['students.id'], ),
                    sa.PrimaryKeyConstraint('email_id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
