"""add students table

Revision ID: c53f7654c0ba
Revises: dccf7228da00
Create Date: 2022-01-09 08:33:55.371280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c53f7654c0ba'
down_revision = 'dccf7228da00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text(
                        'uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('gender', sa.String(), nullable=True),
                    sa.Column('state', sa.String(), nullable=True),
                    sa.Column('department', sa.String(), nullable=True),
                    sa.Column('birth_date', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False)
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
